migrate:
	python manage.py makemigrations
	python manage.py migrate

run:
	python manage.py runserver

createsuperuser:
	python manage.py createsuperuser

test:
	python manage.py test

shell:
	python manage.py shell