version: '3.9'

services:
  postgres:
    build: ./storage
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./storage/init.sql:/docker-entrypoint-initdb.d/init.sql

  django:
    build: .
    container_name: my_django
    restart: always
    depends_on:
      - postgres
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DATABASE_URL: postgres://admin:admin@postgres:5432/mydb
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  pgdata:
